---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hocs-alfresco
  labels:
    version: {{.VERSION}}
spec:
  replicas: {{.REPLICAS}}
  selector:
    matchLabels:
      name: hocs-alfresco
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: hocs-alfresco
        
        version: {{.VERSION}}
    spec:
      securityContext:
        fsGroup: 998
        runAsUser: 1000
      imagePullSecrets:
        - name: registrykey
      initContainers:
        - name: truststore
          image: quay.io/ukhomeofficedigital/cfssl-sidekick-jks:v0.0.6
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - SETUID
                - SETGID
          args:
            - --certs=/certs
            - --command=/usr/bin/create-keystore.sh /certs/tls.pem /certs/tls-key.pem /etc/ssl/certs/acp-root.crt
            - --domain=hocs-alfresco.${KUBE_NAMESPACE}.svc.cluster.local
            - --domain=localhost
            - --onetime=true
          env:
          - name: KUBE_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          volumeMounts:
          - name: certs
            mountPath: /certs
          - name: keystore
            mountPath: /etc/keystore
          - name: bundle
            mountPath: /etc/ssl/certs
            readOnly: true
      containers:
        - name: certs
          image: quay.io/ukhomeofficedigital/cfssl-sidekick:v0.0.6
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - SETUID
                - SETGID
          args:
            - --certs=/certs
            - --domain=hocs-alfresco.${KUBE_NAMESPACE}.svc.cluster.local
            - --expiry=8760h
            - --command=/usr/local/scripts/trigger_nginx_reload.sh
          env:
            - name: KUBE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: certs
              mountPath: /certs
            - name: bundle
              mountPath: /etc/ssl/certs
              readOnly: true

        - name: proxy
          image: quay.io/ukhomeofficedigital/nginx-proxy:v3.4.2
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - SETUID
                - SETGID
          resources:
            limits:
              memory: 512Mi
              cpu: 350m
            requests:
              memory: 256Mi
              cpu: 250m
          env:
            - name: CLIENT_MAX_BODY_SIZE
              value: '15'
            - name: PROXY_SERVICE_HOST
              value: '127.0.0.1'
            - name: PROXY_SERVICE_PORT
              value: '8080'
            - name: NAXSI_USE_DEFAULT_RULES
              value: 'FALSE'
            - name: ENABLE_UUID_PARAM
              value: 'FALSE'
            - name: HTTPS_REDIRECT
              value: 'FALSE'
            # - name: BASIC_AUTH
            #   value: /etc/nginx/authsecrets/htpasswd
            - name: SERVER_CERT
              value: /certs/tls.pem
            - name: SERVER_KEY
              value: /certs/tls-key.pem
            - name: ADD_NGINX_SERVER_CFG
              value: 'location = /reload { allow 127.0.0.1; deny all; content_by_lua_block { os.execute("touch /tmp/nginx-reload-triggered; /usr/local/openresty/nginx/sbin/nginx -s reload; touch /tmp/nginx-reload-complete;") } }'
          volumeMounts:
            - name: certs
              mountPath: /certs
              readOnly: true
            # - name: secrets
            #   mountPath: /etc/nginx/secrets
            #   readOnly: true
            # - name: auth-secrets
            #   mountPath: /etc/nginx/authsecrets
            #   readOnly: true
          ports:
            - name: https
              containerPort: 10443
        - name: hocs-alfresco
          image: quay.io/ukhomeofficedigital/hocs-alfresco:{{.VERSION}}
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            fsGroup: 998
            runAsUser: 1000
          env:
            - name: ALF_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-mysql-rds
                  key: endpoint
            - name: ALF_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-mysql-rds
                  key: port
            - name: ALF_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-mysql-rds
                  key: default_db
            - name: ALF_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-mysql-rds
                  key: username
            - name: ALF_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-mysql-rds
                  key: password
            - name: ALF_S3_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-alfresco-content-s3
                  key: access_key_id
            - name: ALF_S3_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-alfresco-content-s3
                  key: secret_access_key
            - name: ALF_S3_SSEKEY
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-alfresco-content-s3
                  key: kms_key_id
            - name: ALF_S3_BUCKETNAME
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-alfresco-content-s3
                  key: name
            - name: ALF_ADMIN_INITIAL_PASSWORD
              value: 209c6174da490caeb422f3fa5a7ae634
            - name: ALF_REPORTING_ENDPOINT
              value: https:\/\/hocs-reporting-service\.{{.KUBE_NAMESPACE}}\.svc\.cluster\.local
            - name: ALF_NOTIFY_APIKEY
              valueFrom:
                secretKeyRef:
                  name: hocs-alfresco
                  key: notifyApiKey
            - name: ALF_NOTIFY_WF_TEMPLATE_ID
              valueFrom:
                secretKeyRef:
                  name: hocs-alfresco
                  key: notifyWFTemplateId
            - name: ALF_NOTIFY_RESET_PW_TEMPLATE_ID
              valueFrom:
                secretKeyRef:
                  name: hocs-alfresco
                  key: notifyResetPWTemplateId
            - name: ALF_NOTIFY_BULK_USER_IMPORT_TEMPLATE_ID
              valueFrom:
                secretKeyRef:
                  name: hocs-alfresco
                  key: notifyBulkUserImportTemplateId
            - name: ALF_NOTIFY_CREATE_CASE_EMAIL_TEMPLATE_ID
              valueFrom:
                secretKeyRef:
                  name: hocs-alfresco
                  key: notifyCreateCaseEmailTemplateId
          resources:
            limits:
              cpu: 4
              memory: 20Gi
            requests:
              cpu: 2
              memory: 15Gi
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - mountPath: /data
              name: keystore
              readOnly: true
            - mountPath: /usr/local/alfresco/alf_data
              name: alfrescodata
      volumes:
        - name: keystore
          emptyDir:
            medium: "Memory"
        - name: certs
          emptyDir:
            medium: "Memory"
        - name: bundle
          configMap:
            name: bundle
        - name: alfrescodata
          persistentVolumeClaim:
            claimName: hocs-alfresco-pvc
