kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hocs-alfresco-pvc
spec:
  storageClassName: gp2-encrypted
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi