apiVersion: v1
kind: Service
metadata:
 labels:
   name: hocs-data-service
 name: hocs-data-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 10443
  selector:
    name: hocs-data-service
