---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: hocs-alfresco
  name: hocs-alfresco
spec:
  ports:
  - name: https
    port: 8080
    targetPort: 10443
  selector:
    name: hocs-alfresco
