---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: hocs-alfresco
  name: hocs-alfresco
spec:
  ports:
  - name: https
    port: 443
    targetPort: 10443
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    name: hocs-alfresco
