---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: hocs-alfresco
  name: hocs-alfresco
spec:
  ports:
  - name: http
    port: 80
    targetPort: 10080
  - name: https
    port: 443
    targetPort: 10443
  selector:
    name: hocs-alfresco
